import { IoReactNativeCie } from '../native';
import { type LogMode } from './types';

/**
 * Sets the log mode for the CIE SDK.
 *
 * **Note**: Logging is only supported on iOS. On Android, this method will throw an error.
 *
 * @param mode - The log mode to set ('disabled' or 'enabled')
 * @example
 * ```typescript
 * CieManager.setLogMode('enabled');
 * ```
 */
const setLogMode = (mode: LogMode) => {
  IoReactNativeCie.setLogMode(mode);
};

/**
 * Retrieves the file path of the latest logs generated by the CIE SDK.
 * @returns A promise that resolves to a string representing the file path of the latest logs.
 * @throws {CieError} If cannot retrieve the logs path.
 */
const getLogsFilePath = async (): Promise<string> => {
  return IoReactNativeCie.getLogsFilePath();
};

/**
 * Retrieves the contetent of the latest logs generated by the CIE SDK.
 * @returns A promise that resolves to a string representing the content of the latest logs.
 * @throws {CieError} If cannot retrieve the logs content.
 */
const getLogs = async (): Promise<string> => {
  return IoReactNativeCie.getLogs();
};

export { setLogMode, getLogsFilePath, getLogs };
